### ISSUE TITLE
TypeError raised when the query ends with a semicolon

### ISSUE THREAD

**Issue by stfox13** [anecdotes-ai/snowflake-query#6]
# Overview
I'm using this Github Action to create test schemas. Relevant workflow YAML information:

```
on:
  pull_request:
    branches: [ develop, master ]

jobs:
  lint_and_test:
    env: {relevant environment variables set here}
    runs-on: ubuntu-latest
```

An example of the working step can be found below:
```
   steps:
    - name: Create test schemas
      uses: anecdotes-ai/snowflake-query@1.1
      with:
        snowflake_account: ${{ env.SNOWFLAKE_TEST_DB_ACCOUNT }}
        snowflake_warehouse: ${{ env.SNOWFLAKE_TEST_DB_WAREHOUSE }}
        snowflake_username: ${{ env.SNOWFLAKE_TEST_DB_USERNAME }}
        snowflake_password: ${{ env.SNOWFLAKE_TEST_DB_PASSWORD }}
        snowflake_role: ${{ env.SNOWFLAKE_TEST_DB_ROLE }}
        queries: 'CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_MODELING_SCHEMA }}";
          CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_LINEUP_SOURCE_DATA_SCHEMA }}";
          CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_DBT_SCHEMA }}";
          CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_CORE_SCHEMA }}"'
```

During the development process, I attempted to execute multiple queries using the following (NOTE: the last query ends with a semicolon):

```
        queries: 'CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_MODELING_SCHEMA }}";
          CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_LINEUP_SOURCE_DATA_SCHEMA }}";
          CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_DBT_SCHEMA }}";
          CREATE SCHEMA IF NOT EXISTS "${{ env.TEST_DB_NAME }}"."${{ env.TEST_CORE_SCHEMA }}";'
```

I received the following error message:

```
Traceback (most recent call last):
  File "/app/main.py", line 54, in <module>
    main()
  File "/app/main.py", line 39, in main
    json_results = asyncio.run(utils.gather_all_results(query_results))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/utils.py", line 34, in gather_all_results
    for row in done_task.result():
  File "/app/snowflake_connector.py", line 64, in fetch_results
    while self.is_query_running():
  File "/app/snowflake_connector.py", line 48, in is_query_running
    return (self.con.get_query_status(self.query_id) == QueryStatus.RUNNING or
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1397, in get_query_status
    status, status_resp = self._get_query_status(sf_qid)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1367, in _get_query_status
    uuid.UUID(sf_qid)
  File "/usr/local/lib/python3.8/uuid.py", line 165, in __init__
    raise TypeError('one of the hex, bytes, bytes_le, fields, '
TypeError: one of the hex, bytes, bytes_le, fields, or int arguments must be given
```

# Potential Remediation
Don't think this is a big issue, but maybe just update documentation to alert future users of this issue.

**Comment by dapollak** [comment]
Thanks, i'll update the doc

**Comment by stfox13** [comment]
TY - big fan BTW.
